# Generated by Django 5.1.5 on 2025-01-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_person_other_owner', 'Pozwala zobaczyć modele Osoba innych właścicieli')], 'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
    ]
